export const APP_TITLE = process.env.REACT_APP_TITLE
export const APP_DESCRIPTION_TEXT = process.env.REACT_APP_DESCRIPTION_TEXT
export const MENU_TITLE = 'Menu'

export const LOGIN_BUTTON_TEXT = 'Masuk'
export const LOGIN_DESCRIPTION_TEXT ='Temukan yang Anda cari di Ruang Baca TI UHO!'
export const LOGOUT_TEXT = 'Keluar'

export const LOCATION_TEXT = 'Kampus Hijau Bumi Tridharma Andounohu Kendari, 93132 Kompleks gedung Fakultas Teknik, Universitas Halu Oleo, Jurusan Teknik Informatika'
export const EMAIL = 'tif@uho.ac.id'
export const PHONE = '+6812 4377 7734' 

export const CODE = {
  200: 'success',
  201: 'success',
  202: 'info',
  203: 'warn',
  204: 'warn',
  205: 'info',
  206: 'info',
  400: 'error',
  401: 'warn',
  403: 'warn',
  404: 'info',
  405: 'error',
  406: 'error',
  408: 'error',
  415: 'warn',
  428: 'warn',
  429: 'error',
  500: 'error',
  501: 'error',
  502: 'error',
  503: 'error',
  504: 'error',
}

export const TEXT = {
  USERNAME_IS_REQUIRED: 'Silahkan Masukkan Username!',
  PASSWORD_IS_REQUIRED: 'Silahkan Masukkan Password!',
  USER_NOT_FOUND: 'User tidak ditemukan!',
  WRONG_PASSWORD: 'Password yang Anda Masukkan Salah!',
  LOGIN_SUCCESS: 'Login Berhasil',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh Token tidak ditemukan!',
  REFRESH_TOKEN_SUCCESS: 'Refresh Token Berhasil!',
  REFRESH_TOKEN_EXPIRED: 'Refresh Token Anda tidak berlaku!',
  REFRESH_TOKEN_INVALID: 'Refresh Token Anda tidak valid!',
  
  CATEGORY_DATA_NOT_FOUND: 'Data Kategori tidak ditemukan!',
  LIST_CATEGORY: 'Data Kategori ditemukan!',
  NAME_IS_REQUIRED: 'Masukkan data nama!',
  FAILED_CREATE_CATEGORY: 'Gagal membuat Kategori!',
  SUCCESS_CREATE_CATEGORY: 'Sukses membuat Kategori!',
  CATEGORY_NOT_FOUND: 'Kategori tidak ditemukan!',
  CATEGORY_FOUND: 'Kategori ditemukan!',
  CATEGORY_UPDATE_FAILED: 'Gagal mengubah Kategori!',
  CATEGORY_UPDATE_SUCCESS: 'Berhasil mengubah Kategori!',
  CATEGORY_DELETE_FAILED: 'Gagal menghapus Kategori!',
  CATEGORY_DELETE_SUCCESS: 'Berhasil menghapus Kategori!',

  DOCUMENT_DATA_NOT_FOUND: 'Data Dokumen tidak ditemukan!',
  LIST_DOCUMENT: 'Data Dokumen ditemukan!',
  FAILED_CREATE_DOCUMENT: 'Gagal membuat Dokumen!',
  SUCCESS_CREATE_DOCUMENT: 'Sukses membuat Dokumen!',
  DOCUMENT_NOT_FOUND: 'Dokumen tidak ditemukan!',
  DOCUMENT_FOUND: 'Dokumen ditemukan!',
  DOCUMENT_UPDATE_FAILED: 'Gagal mengubah Dokumen!',
  DOCUMENT_UPDATE_SUCCESS: 'Berhasil mengubah Dokumen!',
  DOCUMENT_DELETE_FAILED: 'Gagal menghapus Dokumen!',
  DOCUMENT_DELETE_SUCCESS: 'Berhasil menghapus Dokumen!',

  PENALTY_DATA_NOT_FOUND: 'Data Pelanggaran tidak ditemukan!',
  LIST_PENALTY: 'Data Pelanggaran ditemukan!',
  FAILED_CREATE_PENALTY: 'Gagal membuat Pelanggaran!',
  SUCCESS_CREATE_PENALTY: 'Sukses membuat Pelanggaran!',
  PENALTY_NOT_FOUND: 'Pelanggaran tidak ditemukan!',
  PENALTY_FOUND: 'Pelanggaran ditemukan!',
  PENALTY_UPDATE_FAILED: 'Gagal mengubah Pelanggaran!',
  PENALTY_UPDATE_SUCCESS: 'Berhasil mengubah Pelanggaran!',
  PENALTY_DELETE_FAILED: 'Gagal menghapus Pelanggaran!',
  PENALTY_DELETE_SUCCESS: 'Berhasil menghapus Pelanggaran!',

  RETURN_DATA_NOT_FOUND: 'Data Pengembalian tidak ditemukan!',
  LIST_RETURN: 'Data Pengembalian ditemukan!',
  FAILED_CREATE_RETURN: 'Gagal membuat Pengembalian!',
  SUCCESS_CREATE_RETURN: 'Sukses membuat Pengembalian!',
  RETURN_NOT_FOUND: 'Pengembalian tidak ditemukan!',
  RETURN_FOUND: 'Pengembalian ditemukan!',
  RETURN_UPDATE_FAILED: 'Gagal mengubah Pengembalian!',
  RETURN_UPDATE_SUCCESS: 'Berhasil mengubah Pengembalian!',
  RETURN_DELETE_FAILED: 'Gagal menghapus Pengembalian!',
  RETURN_DELETE_SUCCESS: 'Berhasil menghapus Pengembalian!',

  SPECIALIZATION_DATA_NOT_FOUND: 'Data Peminatan tidak ditemukan!',
  LIST_SPECIALIZATION: 'Data Peminatan ditemukan!',
  FAILED_CREATE_SPECIALIZATION: 'Gagal membuat Peminatan!',
  SUCCESS_CREATE_SPECIALIZATION: 'Sukses membuat Peminatan!',
  SPECIALIZATION_NOT_FOUND: 'Peminatan tidak ditemukan!',
  SPECIALIZATION_FOUND: 'Peminatan ditemukan!',
  SPECIALIZATION_UPDATE_FAILED: 'Gagal mengubah Peminatan!',
  SPECIALIZATION_UPDATE_SUCCESS: 'Berhasil mengubah Peminatan!',
  SPECIALIZATION_DELETE_FAILED: 'Gagal menghapus Peminatan!',
  SPECIALIZATION_DELETE_SUCCESS: 'Berhasil menghapus Peminatan!',

  STORAGE_DATA_NOT_FOUND: 'Data Tempat Penyimpanan tidak ditemukan!',
  LIST_STORAGE: 'Data Tempat Penyimpanan ditemukan!',
  FAILED_CREATE_STORAGE: 'Gagal membuat Tempat Penyimpanan!',
  SUCCESS_CREATE_STORAGE: 'Sukses membuat Tempat Penyimpanan!',
  STORAGE_NOT_FOUND: 'Tempat Penyimpanan tidak ditemukan!',
  STORAGE_FOUND: 'Tempat Penyimpanan ditemukan!',
  STORAGE_UPDATE_FAILED: 'Gagal mengubah Tempat Penyimpanan!',
  STORAGE_UPDATE_SUCCESS: 'Berhasil mengubah Tempat Penyimpanan!',
  STORAGE_DELETE_FAILED: 'Gagal menghapus Tempat Penyimpanan!',
  STORAGE_DELETE_SUCCESS: 'Berhasil menghapus Tempat Penyimpanan!',

  TRANSACTION_DATA_NOT_FOUND: 'Data Peminjaman tidak ditemukan!',
  LIST_TRANSACTION: 'Data Peminjaman ditemukan!',
  FAILED_CREATE_TRANSACTION: 'Gagal membuat Peminjaman!',
  SUCCESS_CREATE_TRANSACTION: 'Sukses membuat Peminjaman!',
  TRANSACTION_NOT_FOUND: 'Peminjaman tidak ditemukan!',
  TRANSACTION_FOUND: 'Peminjaman ditemukan!',
  TRANSACTION_UPDATE_FAILED: 'Gagal mengubah Peminjaman!',
  TRANSACTION_UPDATE_SUCCESS: 'Berhasil mengubah Peminjaman!',
  TRANSACTION_DELETE_FAILED: 'Gagal menghapus Peminjaman!',
  TRANSACTION_DELETE_SUCCESS: 'Berhasil menghapus Peminjaman!',

  USER_DATA_NOT_FOUND: 'Data Pegguna tidak ditemukan!',
  LIST_USER: 'Data Pegguna ditemukan!',
  USER_REGISTER_FAILED: 'Gagal mendaftarkan Pegguna!',
  USER_REGISTER_SUCCESS: 'Sukses mendaftarkan Pegguna!',
  USER_FOUND: 'Pegguna ditemukan!',
  USER_UPDATE_FAILED: 'Gagal mengubah Pegguna!',
  USER_UPDATE_SUCCESS: 'Berhasil mengubah Pegguna!',
  USER_DELETE_FAILED: 'Gagal menghapus Pegguna!',
  USER_DELETE_SUCCESS: 'Berhasil menghapus Pegguna!',
  CHANGE_PASSWORD_USER_FAILED: 'Gagal mengubah password!',
  CHANGE_PASSWORD_USER_SUCCESS: 'Berhasil mengubah password!',
  RESET_PASSWORD_USER_FAILED: 'Reset password pengguna gagal!',
  RESET_PASSWORD_USER_SUCCESS: 'Reset password pengguna berhasil!',
  IMAGE_NOT_FOUND: 'Gambar tidak ditemukan!',
  CHANGE_PROFILE_PICTURE_USER_FAILED: 'Gagal mengubah foto profil pengguna!',
  CHANGE_PROFILE_PICTURE_USER_SUCCESS: 'Berhasil mengubah foto profil pengguna!',

  LIST_MASTER_DATA: 'Data Master ditemukan!',

  ID_REQUIRED: 'ID dibutuhkan!',
  INVALID_ID: 'ID tidak valid!',
  ERROR_QUERY_SEARCH: 'Pencarian Error',

  CODE_IS_REQUIRED: 'Kode Dokuemn dibutuhkan!',
  TITLE_IS_REQUIRED: 'Judul Dokuemn dibutuhkan!',
  WRITER_IS_REQUIRED: 'Penulis Dokuemn dibutuhkan!',
  STORAGE_IS_REQUIRED: 'Tempat Penyimpanan Dokuemn dibutuhkan!',
  DESCRIPTION_IS_REQUIRED: 'Deskripsi dibutuhkan!',
  TRANSACTION_IS_REQUIRED: 'Data Peminjaman dibutuhkan!',
  USER_IS_REQUIRED: 'Data Pengguna dibutuhkan!',
  END_DATE_IS_REQUIRED: 'Data Tanggal Pengembalian dibutuhkan!',
  START_DATE_IS_REQUIRED: 'Data Tanggal Peminjaman dibutuhkan!',
  DOCUMENT_IS_REQUIRED: 'Data Dokumen dibutuhkan!',
  ID_NUMBER_IS_REQUIRED: 'ID Number dibutuhkan!',
  USERNAME_EXIST: 'Username telah digunakan!',
  WRONG_OLD_PASSWORD: 'Password lama yang anda masukkan salah!',
  WRONG_CONFIRM_PASSWORD: 'Konfirmasi Password yang anda masukkan salah!'
}