export const CLEAR_MODAL = 'CLEAR_ALERT'
export const DISPLAY_MODAL = 'SHOW_MODAL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'
export const SET_EDIT = 'SET_EDIT'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'

export const GET_DATA_BEGIN = 'GET_DATA_BEGIN'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'

export const CREATE_DATA_BEGIN = 'CREATE_DATA_BEGIN'
export const CREATE_DATA_ERROR = 'CREATE_DATA_ERROR'
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS'

export const UPDATE_DATA_BEGIN = 'UPDATE_DATA_BEGIN'
export const UPDATE_DATA_ERROR = 'UPDATE_DATA_ERROR'
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS'

export const DELETE_DATA_BEGIN = 'DELETE_DATA_BEGIN'
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR'
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS'